version: '3.4'

services:
  customer-db:
    image: mongo

  notification-db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  fittalks-apigateway:
    image: ${DOCKER_REGISTRY-}fittalks-apigateway
    build:
      context: .
      dockerfile: ApiGateways/FitTalksApiGateway/Dockerfile

  customer-api:
    image: ${DOCKER_REGISTRY-}customer-api
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile


  notification-api:
    image: ${DOCKER_REGISTRY-}notification-api
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile


  health-webstatus:
    image: ${DOCKER_REGISTRY-}health-webstatus
    build:
      context: .
      dockerfile: WebApps/HealthWebStatus/Dockerfile

volumes:
  mongo_data: