version: '3.4'

services:
  fittalksapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  customer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  healthwebstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

