version: '3.4'

services:
  customerdb:
    container_name: customerdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  notificationdb:
    container_name: notificationdb
    environment:
        SA_PASSWORD: "123456Seven"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  fittalksapigateway:
    container_name: fittalksapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - customer.api
        - notification.api
    ports:
      - "7000:80"

  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://customerdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - customerdb
    ports:
      - "7010:80"

  notification.api:
    container_name: notification.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings:NotificationConnectionString=Server=notificationdb;Database=NotificationDb;User Id=sa;Password=123456Seven
        - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
        - WebStatusSettings:NotificationUrl=http://notification.api
    depends_on:
        - notificationdb
        - rabbitmq
    ports:
        - "7020:80"

  healthwebstatus:
    container_name: healthwebstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Customer Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://customer.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Notification Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://notification.api/hc  
    ports:
      - "7007:80"


